### PR TITLE
Moved code to first opencast js module

### PR DESCRIPTION
**Pull request by chfsx**
Hi @ferishili ! As discussed yesterday, I have now moved the JS for the password toggle and introduced a first structure (`il.Opencast`) and for the concrete case `il.Opencast.Form.passwordToggle`.

we can now migrate all JS to this structure.

### CODE REVIEW

**Comment by ferishili** [comment]
How to run that rollup? I assume we need to install the npm deps in the js/opencast folder and run the npx command?
That would be great to make it as easy as and as ready as possible.

**Comment by ferishili** [comment]
For example I am using node v16.15.1 and the output in js/opencast/dist/index.js is slightly different than the one you provided.
So in this case and to avoid such thing, isn't it better to also provide all the locks and modules etc.?

**Comment by chfsx** [comment]
i have npx in version `10.1.0` and rollup `v2.18.0`. of course we could do this as a dependency in the repo, but since we also deliver the code, this dev-dependency would then also be present everywhere the plugin is used. maybe we have to live with the fact that the output is a bit different depending on the version.
a short readme on how to use rollup here exactly would certainly be important. and also how we want to build and structure the modules. i can try to write something here, or do you want to create that?

**Comment by ferishili** [comment]
All right, great, thanks for the explanation, please go ahead with the documentation as I just started using it :D

**Pull request merged**
